name:                parser-generator
version:             0.1.0.0
github:              "Github username here/parser-generator"
license:             BSD3
author:              "Author name here"
maintainer:          "Author email here"
copyright:           "2019 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Github username here/parser-generator#readme>

dependencies:
- base >= 4.7 && < 5
- regex-tdfa
- lens
- containers

library:
  source-dirs: src

executables:
  parser-generator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parser-generator

tests:
  Delete-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - parser-generator
      - tasty-hspec
      - tasty-hedgehog
      - tasty
      - hspec
      - hedgehog
